title: AI Apps and Agents
description: This lab teaches you how to design and build AI applications and agents using Azure AI Foundry. You will learn how to create AI-powered applications that can interact with users, process natural language, and perform tasks based on user guidance. You will also learn how to monitor, troubleshoot, and perform red teaming activities against agents.
theme: just-the-docs

# url: https://microsoft.github.io/TechWorkshop-L300-AI-Apps-and-agents/

aux_links:
  "TechWorkshop L300: AI Apps and Agents": 
    - "https://github.com/microsoft/TechWorkshop-L300-AI-Apps-and-agents"
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note 
    color: purple
  warning:
    title: Warning
    color: red