name: Deploy Interior Design Agent

on:
  push:
    branches: [ main ]
    paths:
      - 'src/app/agents/interiorDesignAgent_initializer.py'
      - 'src/prompts/InteriorDesignAgentPrompt.txt'
      - 'src/app/tools/imageCreationTool.py'
  workflow_dispatch:

jobs:
  deploy-interior-design-agent:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Setup Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Install Python dependencies
      run: |
        cd src
        pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create environment file for agent deployment
      run: |
        cd src
        cat > .env << 'EOF'
        # Azure AI Agent Service credentials
        AZURE_AI_AGENT_ENDPOINT="${{ secrets.AZURE_AI_AGENT_ENDPOINT }}"
        AZURE_AI_AGENT_MODEL_DEPLOYMENT_NAME="${{ secrets.AZURE_AI_AGENT_MODEL_DEPLOYMENT_NAME }}"
        AZURE_AI_AGENT_API_VERSION="${{ secrets.AZURE_AI_AGENT_API_VERSION }}"
        
        # Azure OpenAI for image generation tool
        AZURE_OPENAI_ENDPOINT="${{ secrets.AZURE_OPENAI_ENDPOINT }}"
        AZURE_OPENAI_KEY="${{ secrets.AZURE_OPENAI_KEY }}"
        AZURE_OPENAI_API_VERSION="${{ secrets.AZURE_OPENAI_API_VERSION }}"
        EOF
        
    - name: Deploy Interior Design Agent
      run: |
        cd src
        echo "🚀 Deploying Interior Design Agent..."
        python app/agents/interiorDesignAgent_initializer.py
        
    - name: Verify deployment
      run: |
        echo "✅ Interior Design Agent deployment completed successfully!"
        echo "📋 Files that triggered this deployment:"
        echo "   - interiorDesignAgent_initializer.py"
        echo "   - InteriorDesignAgentPrompt.txt"  
        echo "   - imageCreationTool.py (tool)"
        echo "📊 Commit: ${{ github.sha }}"
        echo "🔗 Run: ${{ github.run_id }}"